GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/686d77d575e3e100a9864989
###
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@example.com",
  "favoriteColor": "purple",
  "birthday": "1995-06-15"
}

###
PUT http://localhost:3000/contacts/686d77d575e3e100a986498a
Content-Type: application/json

{
  "firstName": "Johnny",
  "lastName": "Doe",
  "email": "johnny@example.com",
  "favoriteColor": "Red",
  "birthday": "1995-06-15"
}
###
DELETE http://localhost:3000/contacts/6884224a082ddad95d1fb319
